
/* 
 * Copyright 2024 Rune Berg (http://runeberg.io | https://github.com/1runeberg)
 * Licensed under Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
 * SPDX-License-Identifier: Apache-2.0
*/

#pragma once

#include <vector>
#include <cinttypes>

#include <project_config.h>			// Generated by cmake from project_config.h.in
#include <xrlib/common.hpp>

namespace xrlib
{
	typedef uint32_t XrVersion32;
	typedef uint64_t XrHandleType;

}